Repository vega/vega-datasets, pull requests merged in 2024-12, with the labels that each got.

#647 ci: adds `taplo.toml`, `pyproject.toml`
  .github/workflows/test.yml
  pyproject.toml
  taplo.toml
  uv.lock
Labels: github_actions

#643 feat: replace `SOURCES.md` with `datapackage.md`
  README.md
  SOURCES.md
  _data/datapackage_additions.toml
  _data/templates/package-table.md
  _data/templates/resource-table.md
  datapackage.json
  datapackage.md
  pyproject.toml
  scripts/build_datapackage.py
Labels: enhancement

#650 chore!: Rename `weather.json` -> `weekly-weather.json`
  _data/datapackage_additions.toml
  data/weekly-weather.json
  datapackage.json
  datapackage.md
  src/urls.ts
Labels: maintenance

#651 docs: adds `Resource.bytes` in `datapackage.json`
  datapackage.json
  datapackage.md
  scripts/build_datapackage.py
Labels: documentation

#653 fix: fix `CRLF`-inflated `Resource.bytes` size
  .gitattributes
  datapackage.json
  datapackage.md
Labels: maintenance

#656 fix: Change default `.arrow` compression to `"uncompressed"`
  data/flights-200k.arrow
  datapackage.json
  datapackage.md
  scripts/flights.py
Labels: bug
